import type { Service } from "@/lib/services";

export const servicesEn: Service[] = [
  {
    slug: "developer-handover",
    title: "Developer property handover inspection",
    short: "Primary market — apartments and houses directly from the developer.",
    description:
      "Comprehensive technical inspection of an apartment or house before signing the handover protocol. We verify compliance with Polish Standards, the developer agreement, and the architectural design.",
    bullets: [
      "Dimension compliance verification against the architectural floor plan",
      "Installation layout inspection (electrical, plumbing, ventilation)",
      "Moisture testing of plaster, screeds, and floor finishes",
      "Thermal imaging — detection of thermal bridges",
      "Defect protocol compliant with the Developer Act",
    ],
    checklist: [
      { title: "Plasterwork", description: "Finish standard, flatness and angles, and moisture content" },
      { title: "Floor finishes", description: "Finish standard, flatness and angles, and moisture content" },
      { title: "Window joinery", description: "Installation quality, mechanical damage, glazing condition" },
      { title: "Door joinery", description: "Installation quality, mechanical damage, compliance with specification" },
      { title: "Unit dimensions", description: "Compliance with the architectural floor plan" },
      { title: "External and internal window sills", description: "Installation quality, mechanical damage, draughts" },
      { title: "Electrical, plumbing, heating, and ventilation systems", description: "Compliance with design, power present at electrical points" },
      { title: "Balcony, terrace, garden", description: "Workmanship quality, railings and fencing, compliance with specification" },
      { title: "Parking space", description: "Compliance with standards, workmanship quality" },
      { title: "Storage unit", description: "Workmanship quality, locking and security" },
      { title: "Common areas adjacent to the apartment", description: "Stairwell and corridor quality" },
    ],
    tools: [
      "Thermal imaging camera",
      "Cross-line laser — detection of wall and screed deviations",
      "Moisture meter",
      "Laser distance meter for dimension verification",
      "Anemometer for ventilation checks",
    ],
    image: "/oferta-deweloper-mieszkanie.jpg",
    imageAlt: "Moisture measurement during a technical apartment handover",
    tag: "Primary market",
    price: "from 700 PLN",
    icon: "key",
  },
  {
    slug: "secondary-market-inspection",
    title: "Secondary market property inspection",
    short: "Buying a used apartment or house? We will assess its technical condition.",
    description:
      "Independent technical assessment before purchase or rental. We identify realistic renovation costs and negotiation points with the seller.",
    bullets: [
      "Assessment of installations and finishes",
      "Detection of hidden defects (moisture, finish damage)",
      "Thermal imaging survey — detection of heat loss",
      "Estimated renovation cost valuation — additional service",
      "PDF report within 24 hours",
    ],
    checklist: [
      { title: "Walls and ceilings", description: "Visible damage, delaminating finishes, signs of damp" },
      { title: "Electrical installation", description: "Age of installation, fuses, earthing, cable condition" },
      { title: "Plumbing installation", description: "Pipe integrity, riser condition, water pressure, drains" },
      { title: "Heating and ventilation", description: "Boiler efficiency, radiators, ventilation duct clearance" },
      { title: "Moisture and damp", description: "Detection of hidden damp in walls, ceilings, and floors" },
      { title: "Thermal insulation", description: "Thermal bridges, window and door air leakage" },
      { title: "Roof and façade", description: "Roof covering, gutters, flashings, and façade condition" },
      { title: "Window and door joinery", description: "Damage, draughts, seal and hardware condition" },
      { title: "Floors and ceilings", description: "Deflection, scratches, delamination of finish layers" },
      { title: "Basement and garage", description: "Damp, floor and wall condition, ventilation" },
    ],
    tools: [
      "Thermal imaging camera",
      "Moisture meter",
      "Cross-line laser",
      "Inspection camera for pipes and hard-to-reach areas",
      "Laser distance meter",
    ],
    image: "/oferta-deweloper-protokol.jpg",
    imageAlt: "Technical property handover protocol",
    tag: "Secondary market",
    price: "from 399 PLN",
    icon: "home",
  },
  {
    slug: "thermal-imaging",
    title: "Thermal imaging surveys",
    short: "Thermal imaging survey — detection of heat loss and moisture.",
    description:
      "Professional thermal imaging surveys detect thermal bridges, insulation leaks, underfloor heating defects, and moisture problems invisible to the naked eye.",
    bullets: [
      "Professional thermal imaging survey with photographic documentation",
      "Detection of thermal bridges and window leaks",
      "Underfloor heating diagnostics",
      "Detection of damp and leaks",
      "Report with thermograms and recommendations",
    ],
    checklist: [
      { title: "Thermal bridges", description: "Detection of heat loss through building partitions" },
      { title: "Window and door leaks", description: "Location of draughts and faulty seals" },
      { title: "External wall insulation", description: "Assessment of insulation effectiveness and installation quality" },
      { title: "Underfloor heating", description: "Pipe system diagnostics — cracks, blockages, uneven heating" },
      { title: "Damp and leaks", description: "Location of active and historical damp in partitions" },
      { title: "Concealed installations", description: "Routing of pipes and electrical cables in walls" },
      { title: "Roof and ceiling", description: "Heat loss through the roof plane and top-floor ceiling" },
    ],
    tools: [
      "Thermal imaging camera",
    ],
    image: "/oferta-termowizja.jpg",
    imageAlt: "Thermal imaging survey of a property",
    tag: "Thermal imaging",
    price: "from 249 PLN",
    icon: "thermal",
  },
  {
    slug: "investment-advisory",
    title: "Investment advisory and finishing supervision",
    short: 'Engineer support during renovation and turnkey fit-out.',
    description:
      "Supervision of finishing crews, quality control of works, and material and technical advisory. We protect your budget and schedule.",
    bullets: [
      "Cost estimate and schedule verification",
      "Weekly progress monitoring",
      "Stage handovers (installations, plaster, screeds, finishing)",
      "Material and technical advisory",
      "Client representation in contact with contractors",
    ],
    checklist: [
      { title: "Cost estimate review", description: "Assessment of pricing reliability and market rate compliance" },
      { title: "Work schedule", description: "Analysis of timeline feasibility and work sequencing" },
      { title: "Installation handover", description: "Electrical, plumbing, and ventilation checks before closing up" },
      { title: "Plaster and screed handover", description: "Flatness, angles, moisture before further works" },
      { title: "Finishing quality control", description: "Quality of tiles, floors, painting, and joinery" },
      { title: "Material advisory", description: "Material selection aligned with technical requirements and budget" },
      { title: "Final settlement", description: "Invoice verification and final handover with the contractor team" },
    ],
    tools: [
      "Cross-line laser for level and plumb checks",
      "Moisture meter",
      "Laser distance meter",
      "Thermal imaging camera (optional)",
    ],
    image: "/oferta-doradztwo.jpg",
    imageAlt: "Two people reviewing architectural drawings",
    tag: "Advisory",
    price: "from 199 PLN / visit",
    icon: "compass",
  },
  {
    slug: "premium-legal-package",
    title: "Premium Package: Solicitor + Technical inspection",
    short: "Developer agreement review by a solicitor plus technical inspection in one package.",
    description:
      "Comprehensive investor protection — analysis of the developer agreement by a solicitor specialising in construction law, plus a full technical property inspection.",
    bullets: [
      "Developer agreement analysis by a solicitor",
      "Identification of prohibited clauses and risks",
      "Full technical inspection of apartment or house",
      "Legal support during negotiations with the developer",
      "Assistance with the protocol and subsequent claims",
    ],
    checklist: [
      { title: "Developer agreement analysis", description: "Review of terms for prohibited clauses and risks" },
      { title: "Information prospectus", description: "Verification that the prospectus matches the actual investment" },
      { title: "Contractual penalties and deadlines", description: "Assessment of timeline feasibility and penalty proportionality" },
      { title: "Variation clauses", description: "Analysis of clauses allowing the developer to change the design" },
      { title: "Negotiation recommendations", description: "Specific terms to remove or amend before signing" },
      { title: "Full technical inspection", description: "All developer handover checkpoints — plaster, floors, installations, etc." },
      { title: "Unified legal and engineering report", description: "One document combining legal and technical findings" },
    ],
    tools: [
      "Thermal imaging camera",
      "Cross-line laser",
      "Moisture meter",
      "Legal analysis by a solicitor",
    ],
    image: "/oferta-deweloper-mieszkanie.jpg",
    imageAlt: "Premium Package — legal analysis and technical inspection",
    tag: "Premium",
    price: "from 899 PLN",
    premium: true,
    badge: "New",
    icon: "shield",
  },
  {
    slug: "architectural-surveys",
    title: "Architectural surveys",
    short: "Professional as-built measurements and CAD technical drawings.",
    description:
      "We carry out precise architectural and building surveys essential for renovations, conversions, change-of-use projects, and interior design.",
    bullets: [
      "Laser distance measurement with ±2 mm accuracy",
      "CAD drawings (floor plans, sections, elevations)",
      "3D scanning for heritage buildings (optional)",
      "Documentation ready for submission to authorities",
      "DWG, DXF, or PDF format",
    ],
    checklist: [
      { title: "Dimensional survey", description: "Room lengths, widths, and heights with ±2 mm accuracy" },
      { title: "Floor plans", description: "Accurate plans including niches, columns, and partitions" },
      { title: "Sections and elevations", description: "Section drawings and building elevation views" },
      { title: "Opening schedule", description: "Location and dimensions of windows, doors, and service openings" },
      { title: "Visible installations", description: "Routing of visible installations marked on plans" },
      { title: "Photographic documentation", description: "Photos of each room as a supplement to drawings" },
      { title: "Export to required formats", description: "DWG, DXF, or PDF files ready for further design work" },
    ],
    tools: [
      "Leica laser distance meter with ±1 mm accuracy",
      "Cross-line laser for layout",
      "3D scanner (optional for heritage buildings)",
      "CAD software (AutoCAD / ArchiCAD)",
    ],
    image: "/oferta-doradztwo.jpg",
    imageAlt: "Architectural measurements and technical documentation",
    tag: "Premium",
    price: "from 499 PLN",
    premium: true,
    badge: "New",
    icon: "ruler",
  },
  {
    slug: "energy-performance-certificates",
    title: "Energy audits and performance certificates",
    short: "Energy performance certificate — required for sale and rental.",
    description:
      'We prepare energy performance certificates and comprehensive energy audits, including advisory on thermal modernisation and the "Czyste Powietrze" (Clean Air) programme.',
    bullets: [
      "Energy certificate (apartments, houses, commercial units)",
      "Energy audit for thermal modernisation",
      "Advisory for the Czyste Powietrze programme",
      "Heat source and insulation analysis",
      "Registration in the Central Register of Energy Certificates",
    ],
    checklist: [
      { title: "Building envelope assessment", description: "Analysis of U-values for walls, roofs, and floors" },
      { title: "Window and door joinery", description: "Energy class of windows and doors, thermal bridges in frames" },
      { title: "Heating system", description: "Type, age, and efficiency of heat source and heating installation" },
      { title: "Domestic hot water", description: "Water heater efficiency and DHW pipe insulation" },
      { title: "Ventilation and air conditioning", description: "Ventilation type and its impact on energy balance" },
      { title: "Renewable sources", description: "Presence of photovoltaics, solar collectors, or heat pumps" },
      { title: "EP indicator calculation", description: "Determination of primary energy demand for the building" },
    ],
    tools: [
      "ArCADia-TERMO certification software",
      "Thermal imaging camera (optional — extended audit)",
      "Laser distance meter for volumetric measurements",
    ],
    image: "/oferta-termowizja.jpg",
    imageAlt: "Energy audit and energy performance certificate",
    tag: "Premium",
    price: "from 299 PLN",
    premium: true,
    badge: "New",
    icon: "leaf",
  },
];
